title: "Prepper Paper"
description: "the paper you actually need for COVID-19"
url: "https://prepperpaper.com"
homepage: "https://prepperpaper.com"
repository: "kemitchell/prepperpaper.com"
repository_url: "https://github.com/kemitchell/prepperpaper.com"
collections:
  states:
    output: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
